SELECT DISTINCT(CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_ID IN (SELECT CAR_ID 
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE LEFT(START_DATE, 7) = '2022-10')
AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;
