SELECT E.ID, IFNULL(S.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E
LEFT OUTER JOIN (SELECT PARENT_ID, COUNT(*) AS CNT
                 FROM ECOLI_DATA
                 GROUP BY PARENT_ID) AS S
ON E.ID = S.PARENT_ID
ORDER BY ID;
