SELECT E.ID,
CASE WHEN E.P <= 0.25 THEN 'CRITICAL'
WHEN E.P <= 0.5 THEN 'HIGH'
WHEN E.P <= 0.75 THEN 'MEDIUM'
ELSE 'LOW' END COLONY_NAME
FROM (
 SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) / (COUNT(*) OVER ()) AS P
 FROM ECOLI_DATA
) E
ORDER BY 1;
