SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO INFO
WHERE NOT EXISTS (SELECT PARENT_ITEM_ID
                  FROM ITEM_TREE TREE
                  WHERE TREE.PARENT_ITEM_ID = INFO.ITEM_ID)
ORDER BY ITEM_ID DESC;
