SELECT IT.ID, NI.FISH_NAME, IT.LENGTH
FROM FISH_NAME_INFO NI
JOIN (SELECT I.ID, I.FISH_TYPE, T.LENGTH
      FROM FISH_INFO I
      JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
            FROM FISH_INFO
            GROUP BY FISH_TYPE) T
      ON I.FISH_TYPE = T.FISH_TYPE AND I.LENGTH = T.LENGTH) AS IT
ON NI.FISH_TYPE = IT.FISH_TYPE
ORDER BY ID;
