SELECT H.DEPT_ID, H.DEPT_NAME_EN, E.AVG_SAL
FROM HR_DEPARTMENT H
JOIN (SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
                 FROM HR_EMPLOYEES 
                 GROUP BY DEPT_ID) AS E
USING(DEPT_ID)
ORDER BY AVG_SAL DESC;
