SELECT P.PRODUCT_CODE, OS.SALES_CNT * P.PRICE AS SALES
FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_CNT
      FROM OFFLINE_SALE
      GROUP BY 1) AS OS
USING(PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE;
