SELECT YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA ED1
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA
      GROUP BY 1) AS ED2
ON YEAR(ED1.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY 1, 2;
