# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC;

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A, (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
										FROM REST_INFO
										GROUP BY FOOD_TYPE) B
WHERE A.FOOD_TYPE = B.FOOD_TYPE
AND A.FAVORITES = B.FAVORITES
ORDER BY FOOD_TYPE DESC;
